---

- name: Create a sandbox instance
  hosts: localhost
  gather_facts: False
  vars:
    keypair: us-jhooker-aws-admin
    instance_type: t2.micro
    security_group: ansible-security-group
    image: ami-0520e698dd500b1d1
    region: us-east-2

    tasks:
    - debug:
        var: hostvars[inventory_hostname]
