---

- name: "debug all vars"
  hosts: localhost
  gather_facts: False
  vars:
    keypair: us-jhooker-aws-admin
    instance_type: t2.micro
    security_group: ansible-security-group
    image: ami-0520e698dd500b1d1
    region: us-east-2

  tasks:
    - debug:
        var: hostvars[inventory_hostname]

    - name: "Provision and launch instances"
      ec2:
        assign_public_ip: true
        group: "{{ security_group }}"
        image: "ami-0e38b48473ea57778"
        instance_tags:
          Name: "{{ siduser }}-lab1"
          mysidlabs: "1"
          mysidlabs_owner: "{{ siduser }}"
          mysidlabs_tier: "lab1"
        instance_type: "{{ instance_type }}"
        key_name: "{{ aws_ssh_key_pair }}"
        region: "{{ region }}"
        vpc_subnet_id: "{{ vpc_subnet }}"
        wait: true
      register: ec2

